id: I38DA73A4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T10:52:36+00:00'
last_modified: '2022-06-07T17:48:47.405705+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN2453
  title: གཟའ་སྐར་ལྷ་ཀླུ་སོགས་ཀྱི་གཟུངས་དང་ཆོ་ག་སྣ་ཚོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B72F:
      image_group_id: I3CN2455
      title: ''
      total_pages: 180
      order: 1
      base_file: B72F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
